---
title: "Welcome to this class!"
format: html
editor: visual
---

This website will walk you through the tutorials for the *Topics in Economics* (1S002) course of Ecole Polytechnique's Bachelor program. The course has 3 main objectives: (i) know the basics of R (ii) manipulate the standard statistical and empirical tools (iii) write an original research output.

> **Practical information**
>
> **TA**: [Mateo Moglia](https://mateomoglia.github.io)
>
> **Schedule**: Wednesday morning (check Synapses regularly for any changes in room).
>
> **Required software**: R and its IDE, RStudio (all free). You may download it [here](https://posit.co/download/rstudio-desktop/). Create a free account to use [Overleaf](https://www.overleaf.com). Bring you own laptop or use the lab's computer. The data used in the tutorials are on Moodle. You will also be able to download to find the solved exercices after each tutorial on Moodle.
>
> **Rules**: Send me an email if you miss the class. You are grown-up adults, I trust you to follow thoroughly the class. Do not hesitate to work in small groups.

::: {.callout-caution collapse="true"}
## Log

-   v1.3 - 25/3/25 - Tutorial 6
-   v1.2 - 8/3/25 - Tutorial 4
-   v1.1 - 25/1/25 - Tutorial 3
-   v1.0 - 23/1/25 - Tutorial 2
-   v0.1 - 7/12/24 - Tutorial 1
-   v0.0 - 5/12/24 - Creation
:::

## Class outline

-   [Tutorial 1](https://mateomoglia.github.io/2025_eco1s002/tutorial1.html#/title-slide) *(February 12, computer session)*
    -   Presentation of the class objectives
    -   First hands on R
    -   First hands on LaTeX
-   [Tutorial 2](https://mateomoglia.github.io/2025_eco1s002/tutorial2.html) *(February 19)*
    -   Baseline Solow model derivations
    -   Solow model extensions
-   [Tutorial 3](https://mateomoglia.github.io/2025_eco1s002/tutorial3.html) *(March 5, computer session)*
    -   Replication of Mankiw et al. (1997)
    -   First hands on the OLS estimator
    -   Estimating the baseline and augmented Solow models
-   [Tutorial 4](https://mateomoglia.github.io/2025_eco1s002/tutorial4.html) *(March 12, computer session)*
    -   OLS bias and Instrumental Variables
    -   Replication of Acemoglu et al. (2010)
    -   Export the results
-   Tutorial 5 *(March 19)*
    -   Discussion on the group project
    -   Q&A
-   [Tutorial 6](https://mateomoglia.github.io/2025_eco1s002/tutorial6.html) *(March 26, computer session)*
    -   Autonomous replication of an IV paper (handed in)
-   Tutorial 7 *(April 2, computer session)*
    -   Treatment effect
    -   Solution of Tutorial 6
-   [Tutorial 8](https://mateomoglia.github.io/2025_eco1s002/tutorial8.html) *(April 9)*
    -   Refresher on utility maximization program
    -   Intertemporal maximization problem
-   [Tutorial 9](https://mateomoglia.github.io/2025_eco1s002/tutorial9.html) *(April 16, computer session)*
    -   Work-leisure trade-off
    -   Women labour force participation
-   [Tutorial 10](https://mateomoglia.github.io/2025_eco1s002/tutorial10.html) *(April 30, computer session)*
    -   How to write the research project
-   [Tutorial 11](https://mateomoglia.github.io/2025_eco1s002/tutorial11.html) *(April 30, computer session)*
    -   Difference-in-differences estimation
    -   Marriage output matrices
    -   Measures of assortative mating
-   Tutorial 12 *(May 14)*
    -   Mock exam correction
-   Tutorial 13 *(May 21)*
    -   Research project
    -   Final Q&A
-   Tutorial 14 *(May 28)*
    -   Restitution of the group projects *(graded)*

## About this site and my inspirations

I created this site for teaching purpose. It is of course perfectible and any constructive comment is more than welcome ([write me an email!](mailto:mateo.moglia@gmail.com)). I took inspiration from these sources:

-   The great [Florian Oswald](https://floswald.github.io) teaching material at Sciences Po. Do not hesitate to check his teaching material (in English)

-   The [tutorials](https://mtes-mct.github.io/parcours-r/) of the French Ministry of Ecology (in French)

-   The infamous online book [Econometrics with R](https://www.econometrics-with-r.org) (in English)