---
title: "Tutorial 8: Maximization program"
format: html
editor: visual
toc: true
toc-title: ""
toc-location: right
---

<style>
.math {
  font-size: small;
}
</style>

In this exercise, we are going to learn:

1.  How to maximize the utility of an agent, under budget constraint.
2.  Augment the standard model with the social multiplier
3.  Augment the model by adding some dynamics

## Standard utility maximization program

A representative agent derives utility from consuming two goods, $x$ and $y$. Each good comes at price $p_x$ and $p_y$, respectively. The agent is also endowed with an income $I$ to spend in each good. 

The utility function is Cobb-Douglas and writes:
$$
U(x,y) = x^\alpha y^\beta 
$$

with $\alpha,\beta>0$. 

1.  Write the budget constraint
2.  Write the utility maximization program

To solve the utility maximization program, we can set up a Lagrangean. The function $\mathcal{L}(.)$ is defined as the objective function minus the product between the budget constraint and a scalar $\lambda \in \mathbb{R}$.

3.  Write the Lagrangean and set the first order conditions (partial derivative with respect to $x$, $y$ and $\lambda$ equal 0) as a system
4.  Solve the system for $x^\star$ and $y^\star$ and express them as a function of income and prices
5.  Compute the indirect utility function $V(x,y) = U(x^\star,y^\star)$
6.  [Bonus] Show that $\lambda^\star = \partial V/\partial I$. Interpret
7.  Compute the elasticity of demand of $x$ with respect to $p_x$, $p_y$ and $I$

The second order condition to reach a local maximum is: $2p_x p_y U_{xy} - U_{xx}p_y^2 - U_{yy} p_x^2 > 0$ (where $U_{xx}$ is the second derivative of $U$ wrt $x$).

8.  For $p_x = 2$, $p_y = 1$, $I=10$, $\alpha=\beta=0.5$ did we reach a (local) maximum?

## Social multiplier

We augment the agent program. Indeed, utility can also increase when surrounded by alike people (eg, if you enjoy playing tennis, you might derive utility from the fact that many people enjoy playing tennis around you). We now assume that $p_y = 1$. Utility now writes $U = U(S,x,y)$. $x$ is affected by the social capital (eg, $x$ is the number of hours during which you play tennis).

1.  Solve the new program. Why does including the social capital does not change the equilibrium condition?
2.  Show that $\partial x / \partial S > 0 \iff U_{xS} > p_x U_{yS}$. Interpret. *Hint: Differentiate both utility function and budget constraint with respect to S. Use the second order condition for local maximum. Reminder the Schwartz theorem: $f_{xy} = f{yx}$.*

## Intertemporal utility maximization

Agents are forward looking and have perfect foresighting. It means that they decide on the optimal  consumption decision at the begining of the period. Agents can either consume or save their income. We consider two discrete periods, 1 and 2. Future value is discounted with parameter $0 < \rho < 1$ (agents always prefer consuming 1 today than 1 tomorrow). We also assume that price is equal to unity and we denote the interest rate $r$.

The utility writes:
$$
U = \log c^1 + \rho \log c^2
$$

In period 1, the agent can consume a quantity $c^1 > 0$ and can save a quantity $S > 0$. Her income is $I^1$. 

1.  Write the budget constraint in period 1.

In period 2, the agent can consume $c^2 \geq 0$. She also obtains an income $I^2$. If she has saved in period 1, she also obtains her savings augmented with the interest rate.

2.  Write the budget constraint in period 2
3.  Write the intertemporal budget constraint by combining both constraints
4.  Solve the program with the Lagrange method (the intertemporal utility function subject to the intertemporal budget constraint)
5.  Interpret the results, especially through a change in $\rho$ and in $r$

